---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.7
  - ruby-head
before_install:
  - gem update --system --no-doc
  - gem install bundler
script:
  - bundle exec rspec
  - bundle exec rubocop
jobs:
  allow_failures:
    - rvm: ruby-head

